[package]
name = "brd"
version = "0.1.0"
edition = "2024"

[dependencies.axum]
version = "0.8.8"

[dependencies]
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
maud = { version = "0.27.0", features = ["axum"] }
tower-http = { version = "0.6.8", features = ["fs"] }
tower = "0.5.2"
