[package]
name = "brd"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "signal"] }
warp = { version = "0.4", features = ["server"] }
maud = { version = "0.27.0", features = ["warp"] }
